### ISSUE TITLE
Hidden folders are included in bag despite includeHidden setted to false

### ISSUE THREAD

**Issue by tiarossi** [LibraryOfCongress/bagit-java#101]
Version :  5.0.3
SO: Windows 7

**When** 
* I run  testBagInPlace at BagCreatorTest 

**Then** 
* I should not see  ".hiddenFolder" at the created bag 

**Error**
At BagCreator::moveDataFilesIfNeeded, _Files.isHidden_ is used to test directory hiddeness.  But from method javadoc "On Windows a file is considered hidden **if it isn't a directory** and the DOS hidden attribute is set."

**Comment by johnscancella** [comment]
Hi @tiarossi,

Thank you for reporting this. It should be fixed in the next release 5.0.5
