### ISSUE TITLE
FetchWriter is not adding line separator

### ISSUE THREAD

**Issue by ThomasJejkal** [LibraryOfCongress/bagit-java#106]
**Given** 
* I use bagit-java 5.0.5
* I try to create a bag using fetch files

**When** 
* I write the bag to disk

**Then** 
* A broken fetch.txt is created without any line breaks

Adding the separator was done before by RelativePathWriter.formatRelativePathString(bagitRootDir, fetchItem.getPath()). Due do removing this step, no path separator is added at all.

**Comment by johnscancella** [comment]
This should be fixed in version 5.0.6
