### ISSUE TITLE
Support for 'repeatable' property of BagIt profiles

### ISSUE THREAD

**Issue by ThomasJejkal** [LibraryOfCongress/bagit-java#107]
According to the [BagIt Profile Specification](https://github.com/ruebot/bagit-profiles) elements listed in BagInfo can have the attribute 'repeatable' if multiple occurences of the according element are allowed. 

Despite of the fact, that [Metadata](https://github.com/LibraryOfCongress/bagit-java/blob/master/src/main/java/gov/loc/repository/bagit/domain/Metadata.java) allows to hold a list of values for each key, neither [BagInfoRequirement](https://github.com/LibraryOfCongress/bagit-java/blob/master/src/main/java/gov/loc/repository/bagit/conformance/profile/BagInfoRequirement.java) contains this value, nor does [BagProfileChecker](https://github.com/LibraryOfCongress/bagit-java/blob/master/src/main/java/gov/loc/repository/bagit/conformance/BagProfileChecker.java) take this property into account while checking the bag.

**Comment by johnscancella** [comment]
Hi @ThomasJejkal, thanks for reporting this. This should be implemented in version 5.1.0

**Comment by UkDv** [comment]
To fix this issue, you can add the following code in `parseBagInfo` function of `BagitProfileDeserializer.java` class

> final JsonNode repeatableNode = node.getValue().get("repeatable");
      if(repeatableNode != null){
        entry.setRepeatable(repeatableNode.asBoolean());
      }
