### ISSUE TITLE
No payload file "data" allowed in BagIt bag creation folder?

### ISSUE THREAD

**Issue by fungunga** [LibraryOfCongress/bagit-java#108]
## When submitting an issue please include:
* Which version you are running of the software you are running
5.0.6
* Which operating system you are running on
Mac OS X High Sierra
* If available Attach all logs, and or output, and or screenshots

## Please format it in the [given when then style](http://martinfowler.com/bliki/GivenWhenThen.html)
For example (from link above):

**Given** 
* With (folder) a folder with files to start the BagIt creation process using:

Path folder = Paths.get(bagFolder.toURI());

Collection<SupportedAlgorithm> algorithm = new ArrayList<SupportedAlgorithm>();
algorithm.add(StandardSupportedAlgorithms.MD5);
bvoolean includeHiddenFiles = false;
Bag bag = BagCreator.bagInPlace(folder, algorithm, includeHiddenFiles);

**When** 
* I name one of the payload files "data" in /folder/

**Then** 
* Shouldn't I get a bag with a file named "data" in the "data/" payload folder?
* I do instead get an FileAlreadyExistsException, that the file "data" already is existing.

**If**
* there is a spec that no files called "data" must be added to the payload, everythin is OK but the error message :-)

**Comment by johnscancella** [comment]
Thanks for submitting this. The problem stems from us creating a data directory to move all the data files into. Since you already have a file named `data`, it fails to create a directory named `data`. This will be fixed in release 5.0.7

**Comment by fungunga** [comment]
Thanks a lot!
