### ISSUE TITLE
"checksums" should be Base64 encoded values

### ISSUE THREAD

**Issue by christopher-johnson** [LibraryOfCongress/bagit-java#111]
According to [rfc3230](https://tools.ietf.org/html/rfc3230#page-9), the specification that defines "Instance Digests", a digest value should be encoded as Base64.  

Rather, the default BagCreator computes message digests and writes these values as hex hashes to the `tagmanifest-{algorithm}.txt` and `manifest-{algorithm}.txt` files.  

Thus, a use case that would read a payload manifest to obtain `Digest` header values for binary write requests could not obtain a comparable Base64 value from the hex hash.  An server that conforms to RFC3230 would not process a `Digest` header with a hex formatted value.  

See https://github.com/trellis-ldp/trellis/wiki/Resource-Validation-(Fixity) for a server implementation.

**Comment by johnscancella** [comment]
Hi @christopher-johnson, thanks for submitting this. Could you please explain your use case more? The [bagit specification](https://tools.ietf.org/html/draft-kunze-bagit) does not list that it is conformant with rfc3230, so seems to me to be new functionality that would significantly break current functionality.

**Comment by johnscancella** [comment]
Thanks for the update. I'm afraid I still don't understand. A `MD5` or other checksum outputs a hex formatted string. The server still needs to compute this checksum and check it against the bits sent. 

1) How does base64 encoding the checksum help?
2) Can't you take the hex string and base64 encode it yourself?

**Comment by christopher-johnson** [comment]
`java.security.MessageDigest.digest() `returns a `byte[]`

A [method in Hasher](https://github.com/LibraryOfCongress/bagit-java/blob/master/src/main/java/gov/loc/repository/bagit/hash/Hasher.java#L85-L94) formats this a hex encoded string.

> The server still needs to compute this checksum and check it against the bits sent.

An [implementation of RFC3230](https://github.com/trellis-ldp/trellis/blob/master/trellis-http/src/main/java/org/trellisldp/http/HttpBasedBinaryService.java#L179-L199) computes the checksum on the input stream and checks it with a client supplied request header value (e.g. `Digest: someBase64string`).

> How does base64 encoding the checksum help?

first to comply with RFC3230 and Base64 is slightly more efficient (Hex will take two characters for each byte - Base64 takes 4 characters for every 3 bytes,)

> Can't you take the hex string and base64 encode it yourself?

that may work, but it puts an extra processing dependency on the reader.  I will be both creating bags and reading them, so for my reader use case, it is a bit cleaner to source a manifest with base64 digests.

**Comment by acdha** [comment]
I would be somewhat surprised if the extra overhead of the reader doing hex to base64 conversion was significant but perhaps the answer here would just be a subclass which could override `formatMessageDigest`? RFC 3230 isn't normative for this spec and the Bag It spec requires the hex encoded format so that can't on by default but it might make sense to either make that configurable or allow access to the underlying `MessageDigest` instance.

**Comment by johnscancella** [comment]
Since this is outside the bagit specification and is possible to work around with minimal performance hit, this is very low priority for me. However, if you feel very strongly, you are always welcome to submit a pull request and I would be glad to work with you on the pull request.
