### ISSUE TITLE
Support for BagIt version 1.0 planned?

### ISSUE THREAD

**Issue by saschaszott** [LibraryOfCongress/bagit-java#145]
I noticed that the current version of bagit-java supports the BagIt specification up to version 0.97. Meanwhile, BagIt version 1.0 has been released, introducing some improvements, such as support for multiple checksum algorithms and stricter definitions for file encodings.

My questions are:
- Is the implementation of BagIt 1.0 planned?
- If yes, is there an estimated timeline for this?

Adding support for BagIt 1.0 would greatly enhance interoperability and compliance with the latest version of the BagIt specification. Thank you for your response and for your work on this important project!

**Comment by jscancella** [comment]
I don't think this is actively maintained anymore, which is why I created https://github.com/jscancella/bagging I hope it is helpful to you

**Comment by saschaszott** [comment]
Hi @jscancella , thank you!
