### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by jar398** [LibraryOfCongress/bagit-java#17]
I cloned and did 'mvn package' and got multiple failures, see: https://gist.github.com/jar398/71ead6abcbbc354e9505

**Comment by johnscancella** [comment]
We now use Gradle as our build tool. Please try again using that if you need to build from source. Otherwise it is advised to download it from the [Latest Release](https://github.com/LibraryOfCongress/bagit-java/releases/latest) page.
