### ISSUE TITLE
Any Java examples?

### ISSUE THREAD

**Issue by Tegomena** [LibraryOfCongress/bagit-java#18]
Dear all,

I'm searching some documentation about how to use the Java Bagit library. Are there any example codes, tutorials etc.? (It seems so that the Java Doc is not complete, class "bag" contains nearly no doc?).
Thank you!
Best,

Tom

**Comment by fungunga** [comment]
Yes, that was I was looking for :-) Found it directly in the Command Line Driver Code... Maybe put it into the README file?

**Comment by johnscancella** [comment]
@ntallman in regards to your question about the future of bagger, we are looking to make it even easier to use with a web(javascript) based version (thus removing the need to install) called [bagger-js](https://github.com/LibraryOfCongress/bagger-js)

**Comment by ntallman** [comment]
+1 @johnscancella!

**Comment by johnscancella** [comment]
@ntallman Also we are planning a rewrite of the library. You can find some great examples here: 
https://github.com/LibraryOfCongress/bagit-java/blob/rewrite/README.md#examples
