### ISSUE TITLE
Handling empty directories

### ISSUE THREAD

**Issue by Tegomena** [LibraryOfCongress/bagit-java#21]
Dear all,

We found a problem when a payload contains an empty directory. The BagIt specification says something about handling empty directories (adding a ".keep" file), maybe the java lib should also act like this? The traceback we get:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at
gov.loc.repository.bagit.writer.impl.FileSystemWriter.removeExtraFiles(FileSystemWriter.java:232)
at
gov.loc.repository.bagit.writer.impl.FileSystemWriter.write(FileSystemWriter.java:222)
at
de.mpg.rzg.tacoharvest.bagit.CreateBagitContainer.createBagIt(CreateBagitContainer.java:37)

Maybe a change in line 239 in gov.loc.repository.bagit.writer.impl.FileSystemWriter should be enough?:

if (recurse && file.listFiles().length > 0) {

**Comment by johnscancella** [comment]
Should be fixed in version 4.11
