### ISSUE TITLE
TarWriter

### ISSUE THREAD

**Issue by fungunga** [LibraryOfCongress/bagit-java#22]
Are there any plans to again implement a TarWriter?

**Comment by johnscancella** [comment]
I don't believe there is. We used to have the capability to do Tars but that was removed in version 4.0. The last version that supports Tar is 3.13 and can be found here
https://github.com/LibraryOfCongress/bagit-java/releases/tag/bagit-3.12

**Comment by fungunga** [comment]
Yes, I saw that and I just completet a TarWriter :-) I think I am just forking this if I only knew why it was taken out... maybe there is a cause to NOT implement a TAR writer??

**Comment by johnscancella** [comment]
Yeah I was trying to pour through our old documentation to see why we pulled it out but have been distracted by other work and meetings today. If I find anything I will be sure to post it here.

**Comment by fungunga** [comment]
It is possible to use TAR according to the Bagit spec, so I just forked the repo and you can have a look into it... I also added an example file to create bags :-)

**Comment by fungunga** [comment]
I just will deploy my TAR version of the bagit to our nexus, just to do testing, hope that is ok...

**Comment by fungunga** [comment]
(ups, forgot the URL, sorry for that…) If someone is interested in testing the TarWriter, please have a look here: http://dev.dariah.eu/nexus/content/repositories/snapshots/gov/loc/bagit/

**Comment by fungunga** [comment]
Are there any plans to use TAR again in one of the next releases? I will just test my fork and implementation further, and post any progress here…

**Comment by johnscancella** [comment]
@fungunga 
Things are kind of in flux at the library right now. While it is possible it will be worked on, realistically I don't see it happening until someone creates a pull request. Feel free to submit one when you think your fork is ready.

**Comment by fungunga** [comment]
Great! Thanks! I'll just add some tests!

**Comment by fungunga** [comment]
I also implemented the Junit tests now, but they still do not work. They were no filesystems back in 3.13, so maybe that was the cause for not implementing TAR, because TAR is based on streams, not on entries? Maybe we should simply use ZIP instead :-)

**Comment by justinlittman** [comment]
When Commons VFS was removed in 4.0, I only implemented zip because I wasn't aware of anyone using tar for bags.

**Comment by fungunga** [comment]
We use the Bagit for long term archiving (what else :-) and thought TAR would be better for restoring invalid packages and was the older standard for archiving files and folders. We just test the ZIP now and keep you informed! Thanks a lot! We also plan to use streaming of parts of files (such as parts of video streams) to not have to deliver the complete video file. We will test this using ZIP streams, too.

**Comment by justinlittman** [comment]
For what it's worth, we encountered problems with tar compatibility across
multiple *nix flavors way back in the Archive Ingest and Handling Test (
http://www.digitalpreservation.gov/partners/aiht.html).  Yes, it's a decade
later and I'm still scarred.

**Comment by fungunga** [comment]
ZIP streaming works just fine, and we are using ZIP now for our repository! Thanks for looking into that issue. Using 4.9.0 now. But I leave my copy for implementing TAR as a fork with beginning TAR support, just in case :)

**Comment by johnscancella** [comment]
@fungunga I know this is old, but thought you might be interested in the [rewrite](https://github.com/LibraryOfCongress/bagit-java/pull/32) since it deals with java.io.File which should be easy to tar. Since it is still a work in progress it may change, but is a good first test.
