### ISSUE TITLE
Remove contact information and mailing list from readme

### ISSUE THREAD

**Issue by kzwa** [LibraryOfCongress/bagit-java#23]
At the bottom of the readme files are contact information that is out of date. The loc-xferutils-mail mailing list is no longer used and the email addresses jlit@loc.gov is no longer valid.

**Comment by nuest** [comment]
I came here searching for a bagit mailing list - is there a successor of the mentioned mailing list or contact email to reach the BagIt community as a whole?

**Comment by justinlittman** [comment]
I'd suggest digital-curation@googlegroups.com or adding a ticket to https://github.com/jkunze/bagitspec.

**Comment by nuest** [comment]
Thanks! A link to the spec repo would be helpful in the readme, and I'll try my luck on the mailing list.
