### ISSUE TITLE
Fetching of non-payload files should not be attempted

### ISSUE THREAD

**Issue by janvanmansum** [LibraryOfCongress/bagit-java#29]
# Scenario:
1. Create a bag
2. Add a fetch line to the `fetch.txt` that has a non-payload destination, e.g., `metadata/file.txt`
3. Execute `bag fillholey` on the bag

# Problem:
The tool reports a failure, but it fetches the file anyway. According to the BagIt-specs [only payload files can be fetched](https://tools.ietf.org/html/draft-kunze-bagit#section-2.2.3). It seems the tools fetches the files and then tries to verify the checksum but, as it assumes that it dealing only with payload files, it only checks the payload manifests and the fails on the missing checksum (even if it is present in the tagmanifest).

# Code example
I created [a JUnit example to demonstrate the problem](https://github.com/janvanmansum/bagit-issue-fetch-non-payload). `mvn test` will now of course fail. See the test code for what I would expect to happen. 

I looked up how the command line driver implements `fillholey`. Depending on the parameters you pass to the fetch-function you get slightly different results.

# Correct behavior?
So, what would be the correct behavior? I suppose the library could either ignore fetch lines aimed at non-payload files or fail on them. At any rate, I find the current results a bit confusing.

**Comment by johnscancella** [comment]
Will be in release 4.11

**Comment by janvanmansum** [comment]
Great! Thanks!
