### ISSUE TITLE
No data folder generated when the payload is empty

### ISSUE THREAD

**Issue by rvanheest** [LibraryOfCongress/bagit-java#36]
Copy from the end of #35:

In case of an empty payload in version 4.11, I notice that the `data` folder is not generated at all, presumably due to the bag being empty/having no payload. Is that the expected behaviour? At first glance I would expect an empty `data` folder to be there, but version 4.11 doesn't do that. In the [BagIt documentation](https://tools.ietf.org/html/draft-kunze-bagit-13#section-2.1.2) however, I read that this `data` folder MUST exist.

Notice that also **NO** `manifest-md5.txt` file is created for a bag with no payload. Again, in the [documentation](https://tools.ietf.org/html/draft-kunze-bagit-13#section-2.1.3) I read "*Every bag MUST contain one payload manifest file, ...*".

**Comment by johnscancella** [comment]
I probably won't be working on this any time soon (if ever) since we are moving forward with the 5.0 series which doesn't have this problem.
