### ISSUE TITLE
Changing example: BagCreator.bagInPlace is static

### ISSUE THREAD

**Issue by Tegomena** [LibraryOfCongress/bagit-java#42]
The README says in "Create a bag from a folder using version 0.97":

BagCreator creator = new BagCreator();
Bag bag = creator.bagInPlace(folder, algorithm, includeHiddenFiles);

-> but BagCreator.bagInPlace seems to be static, so:

Bag bag = BagCreator.bagInPlace(folder, algorithm, includeHiddenFiles);

**Comment by johnscancella** [comment]
Yup you are correct. Let me fix that.
