### ISSUE TITLE
Document hidden folder behavior

### ISSUE THREAD

**Issue by dbrunton** [LibraryOfCongress/bagit-java#46]
Since it's changing, some user docs, and a flag to easily revert to previous behavior.

**Comment by johnscancella** [comment]
@danshim Since you wrote all of that code, would you like to do another pull request with some documentation?

**Comment by danshim** [comment]
Will do

**Comment by danshim** [comment]
John, where did all the java files go?! I pulled and no longer see the java
files under src/main/java/gov/loc/repository/bagit.

**Comment by johnscancella** [comment]
I have seen merged in the new 5.0 branch into master. You will have to do
`git checkout v4.12.0`

**Comment by johnscancella** [comment]
I also just created a branch, if that is easier for you. You can get to it by running
`git fetch upstream`
`git checkout 4.12`

**Comment by johnscancella** [comment]
@dbrunton looks like there is already a flag. I did change it to behave like the old versions (include hidden files/folders) by default and have the flag change that behavior if needed. Same for the BagFactory class, defaults to old behavior. And added a comment on the constructors for anybody using the class.

Is there anything else you wanted for the documentation?
