### ISSUE TITLE
BagVerifier starts user threads that prevent client application from terminating

### ISSUE THREAD

**Issue by janvanmansum** [LibraryOfCongress/bagit-java#49]
To reproduce this problem, compile and execute the following code `BagVerifierTest.java`:

```java
import gov.loc.repository.bagit.domain.Bag;
import gov.loc.repository.bagit.reader.BagReader;
import gov.loc.repository.bagit.verify.BagVerifier;

import java.nio.file.Paths;

public class BagVerifierTest {
    public static void main(String[] args) throws  Exception {
        BagVerifier verifier = new BagVerifier();
        BagReader reader = new BagReader();
        Bag b = reader.read(Paths.get(args[0]));
        verifier.isValid(b, false);
    }
}
```
    javac -cp bagit-5.0-SNAPSHOT.jar:. BagVerifierTest.java
    java -cp bagit-5.0-SNAPSHOT.jar:slf4j-api-1.7.6.jar:. BagVerifierTest <some valid bag>

The problem is that the program doesn't terminate. This is probably due to the instantiation of a thread pool [here](https://github.com/LibraryOfCongress/bagit-java/blob/master/src/main/java/gov/loc/repository/bagit/verify/BagVerifier.java#L162). It uses the [default thread factory](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#defaultThreadFactory--) which creates user (non-daemon) threads. These threads keep running unless you shut them down yourself, and in doing so prevent the application from closing down.

A solution could be to use a custom thread factory instead, that creates daemon threads, or to give the client application a handle to the `ExecutorService` so that it can call [shutdown or shutdownNow](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#shutdownNow--)

**Comment by johnscancella** [comment]
Thanks for finding this. With the latest code this should be fixed. If you would prefer to have access to the  ExecutorService directly we can put in a feature enhancement request.
