### ISSUE TITLE
How to change MD5 checksumming to SHA1

### ISSUE THREAD

**Issue by PaulBoon** [LibraryOfCongress/bagit-java#50]
Using version 4.11 I can create Bags, but these have MD5 checksumming. 
I want to change it to SHA1, but I have no clue how to do that. 
Can you give some example code.

**Comment by johnscancella** [comment]
assuming you are bagging in place, it would be
```
<BAGIT-INSTALL-DIRECTORY>\bin\bagit baginplace <FOLDER-TO-BAG> --payloadmanifestalgorithm sha1 --tagmanifestalgorithm sha1
```
where `<BAGIT-INSTALL-DIRECTORY>` is the folder that appears after unzipping (bagit-4.11.0) and `<FOLDER-TO-BAG>` is the folder on the system that you wish to bag.

For example, for me on windows it would look like
```
C:\Users\jsca\Downloads\bagit-4.11.0\bin\bagit baginplace C:\Users\jsca\Downloads\myBag --payloadmanifestalgorithm sha1 --tagmanifestalgorithm sha1
```

**Comment by PaulBoon** [comment]
Sorry for not being clear about my problem, but I mean creating Bags using the java library. 
My Scala code looks like this:

      val bagFactory = new BagFactory
      val preBag = bagFactory.createPreBag(outputBagDir)
      val bag = bagFactory.createBag(outputBagDir)

      if (inputDirExists) bag.addFilesToPayload(inputDir.listFiles.toList)
      bag.makeComplete

      val fsw = new FileSystemWriter(bagFactory)
      if (!inputDirExists) fsw.setTagFilesOnly(true)
      fsw.write(bag, outputBagDir)

      if (!inputDirExists) preBag.setIgnoreAdditionalDirectories(List(metadataDirName))
      preBag.makeBagInPlace(Version.V0_97, false)

**Comment by PaulBoon** [comment]
The solution is to set the SHA1 algorithm on a 'completer' and pass that to the makeBagInPlace. 
When changed in the code above it looks like this:

      val algorithm = Algorithm.SHA1
      val completer = new DefaultCompleter(bagFactory)
      completer.setTagManifestAlgorithm(algorithm)
      completer.setPayloadManifestAlgorithm(algorithm)

      if (!inputDirExists) preBag.setIgnoreAdditionalDirectories(List(metadataDirName))
      preBag.makeBagInPlace(Version.V0_97, false, completer)

**Comment by johnscancella** [comment]
Sorry about the confusion, but I am glad you were able to figure it out. I am curious, is this for a personal project or for work? You might want to try the latest snapshot release as the api is much nicer.
