### ISSUE TITLE
Unit tests failing on Windows

### ISSUE THREAD

**Issue by smmorrissey** [LibraryOfCongress/bagit-java#53]
Running 5.0.0 on Windows 7, Java 1.8

About 30 unit tests are failing, due to Windows FileSystem differences from UNIX - these include	
- Resolving file path
- Path separators
- File name restrictions (eg. cannot create a Path object with '\r' or '\n'
- Differences in behavior when employing delete() method on a temporary file
- Differences in causing a file or directory to be hidden (must explicitly set property; starting name with "." not enough
- End of line characters in comparisons of expected and actual content

Attached file lists individual tests
[locJunitErrorsAbbrev.docx](https://github.com/LibraryOfCongress/bagit-java/files/592431/locJunitErrorsAbbrev.docx)

**Comment by smmorrissey** [comment]
See also issue #52 
Changes in that commit have been incorporated; test listed above are still failing

**Comment by johnscancella** [comment]
should be fixed now, if it is not please reopen issue
