### ISSUE TITLE
Make hashing more efficient

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagit-java#57]
Currently the bagit-java library re-reads a file for each hash type. This is inefficient, and unnecessary since they could be calculated in parallel.

**Comment by johnscancella** [comment]
example of listing all available hashing algorithms available
```
@Test
  public void foo(){
    for(Provider provider : Security.getProviders()){
      for(Service service : provider.getServices()){
        if(service.getType().equals("MessageDigest")){
          System.err.println(service.getAlgorithm());
        }
      }
    }
  }
```

**Comment by acdha** [comment]
While you're working on this, I noticed that it appears to be hashing in 1KB blocks. I would expect it to be faster using larger sizes, especially on network filesystems or SSDs, so it might be worth bumping that up somewhere in the range of 4-64KB:

https://github.com/LibraryOfCongress/bagit-java/blob/c6080376f4c367fbe446b77e217237b74038ceea/src/main/java/gov/loc/repository/bagit/hash/Hasher.java#L14
