### ISSUE TITLE
When creating manifests for bags on Windows, MUST write the path with Unix file separator

### ISSUE THREAD

**Issue by smmorrissey** [LibraryOfCongress/bagit-java#66]
* Bagit 5.0
* Windows 7
* Java 8

Per specification, when creating manifests for bags, MUST write the path with UNIX file separator ('/').
When run on Windows, this is not happening in BagWriter.writeManifests(): 

 -- output from BagWriterTest:
someHashValue data\one\two\buckleMyShoe.txt

**Comment by johnscancella** [comment]
I must not be fully awake yet... I replaced the newline not the \ in the writer with commit 2bc1883.
