### ISSUE TITLE
Test for malicious manifest on windows 

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagit-java#67]
https://github.com/loc-rdc/bagitspec/blob/bagit1.0/bagit.xml#L783-L785
>  Windows implementations &should; test their implementations to ensure that safety-checks prevent use of drive letters and the less commonly used namespace sequences (e.g. "\\?\C:\…") described in <xref target="MSFNAM"

Does the current set of tests, account for this adequately? If not we should create a windows only test for it.

**Comment by acdha** [comment]
@johnscancella We should probably have a known-invalid bag in https://github.com/loc-rdc/bagit-conformance-suite

**Comment by johnscancella** [comment]
I was thinking more about this, is this even a valid case with the fact that we only allow `/` as the path separator?

**Comment by acdha** [comment]
I think it's a good *invalid* test case: it's easy to imagine an implementation error where the library creates manifests using `/` as expected but passes everything else to the OS directly and on Windows, a path with `/` will be normally be transparently treated as if it used `\` using the normal Win32 APIs.

I think this is a minor problem for manifests – it could allow some information leakage about the existence of files or specific targeted versions – but more of an issue for `fetch.txt` where it could potentially allow overwriting a local file with an arbitrary URL in an automated pipeline.

**Comment by johnscancella** [comment]
if you type in `//?/C:/` into windows it doesn't know what to do, it must use the `\`. So with that in mind I don't think it is even a good invalid test, it is just invalid. As for fetch.txt files, we can add a check to see if the destination is outside the bag just like we do with manifests.

**Comment by acdha** [comment]
Right, but if you put "\\?\C:\" into a bag and something just passes it to a file open call without validation, you have a potential problem unless you validate the path before opening it.

**Comment by nuest** [comment]
I did not check if  that is covered by any already existing test, but what about file URIs, e.g. `file://..` ?

https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by johnscancella** [comment]
@nuest see https://github.com/LibraryOfCongress/bagit-java/commit/30669a020d1bc6016a445f83571d791c93e3b0e8
