### ISSUE TITLE
normalize filename paths

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagit-java#68]
as per https://github.com/loc-rdc/bagitspec/blob/bagit1.0/bagit.xml#L939-L957
> * Implementations SHOULD discourage the creation of bags containing files which differ only in case.
> * Implementations MUST prevent the creation of bags containing files which differ only in normalization form.
> * BagIt implementations SHOULD tolerate differences in normalization form by comparing both the list of filesystem and manifest names after applying the same normalization form to both.
> * Implementations SHOULD issue a warning when multiple manifests are present which differ only in case or normalization form.

needs to be implemented

**Comment by acdha** [comment]
@johnscancella I'm not sure how pedantic we want to be about this but technically 05c5ed557c9d346990096764f1d52fde989fc02c might not be enough if e.g. a filename is inconsistently normalized internally (which might sound odd but is relatively easy to do with filenames which are derived from text content).

**Comment by johnscancella** [comment]
And with that I believe I will call this done.
in case it isn't clear:
> Implementations MUST prevent the creation of bags containing files which differ only in normalization form.
is implemented by the fact that if the manifest differs in normalization then on the filesystem it will fail to open the file when copying.
