### ISSUE TITLE
Enhancement: Controlling number of threads used to verify a bag

### ISSUE THREAD

**Issue by smmorrissey** [LibraryOfCongress/bagit-java#71]
**Given** 
* A bag
* And a requirement to control the number of threads used by Bagit

**When** 
* I ask to verify the bag

**Then** 
* I should be able to specify the number of threads used to do verification

This is getting into the weeds for use cases, but right now the code in `checkAllFilesListedInManifestExist()`

 and `checkHashes()` in BagVerifier are using 
`final ExecutorService executor = Executors.newCachedThreadPool();`

We need something like
`final ExecutorService executor = ExecutorService.newFixedThreadPool(int nThreads) `

We are more than happy to just implement the use case for ourselves in a subclass - -but doing that in a straightforward way would mean making `checkAllFilesListedInManifestExist()` and `checkHashes()` protected methods.

Would that be acceptable?

**Comment by johnscancella** [comment]
BagReader and BagVerifier should not really be subclassed. I would rather see a constructor that takes the executor as a parameter and another that doesn't which would default to the current `Executors.newCachedThreadPool()`

**Comment by johnscancella** [comment]
available as 5.0.0-Dec-14-2016_19-23-14-SNAPSHOT from [maven snapshots repo for bagit](https://oss.sonatype.org/content/repositories/snapshots/gov/loc/bagit/)

**Comment by smmorrissey** [comment]
Even better -- thanks!!
