### ISSUE TITLE
New errors introduced in unit tests when run on windows

### ISSUE THREAD

**Issue by smmorrissey** [LibraryOfCongress/bagit-java#75]
* VERSION:  5.0.0-Dec-16-2016_16-08-28-SNAPSHOT
* Windows 7

**Given** 
* I am running Eclipse on Windows

**When** 
* I want to run all unit test successfully

**Then** 
* Filepaths should resolve correctly for windows and test should run green

FetchItemTest.testToString()
   source of problem line 22:  FetchItem item = new FetchItem(url, 1l, Paths.get("/foo"));
   
BagReaderTest.testReadFileUrlMaliciousManifestThrowsException
	source of problem line 297
		sut.readChecksumFileMap(manifestFile, Paths.get("/bar"), StandardCharsets.UTF_8);
BagReaderTest.foo()
	source of problem line 344    Path p = Paths.get("file:///tmp");
BagReaderTest.testReadFileUrlMaliciousFetchThrowsException
	sut.readFetch(fetchFile, StandardCharsets.UTF_8, Paths.get("/bar"));

**Comment by johnscancella** [comment]
should be fixed now.
