### ISSUE TITLE
Failure to close DirectoryStream objects results in file descriptors remaining open

### ISSUE THREAD

**Issue by smmorrissey** [LibraryOfCongress/bagit-java#83]
The following methods create, but do not close, DirectoryStream objects, which result in open file descriptors remaining after bags are created/verified:

gov.loc.repository.bagit.conformance.ManifestChecker.checkManifests(0
gov.loc.repository.bagit.creator.BagCreator.bagInPlace()
gov.loc.repository.bagit.reader.ManifestReader.readAllManifests()
gov.loc.repository.bagit.verify.CheckIfFileExistsTask.existsNormalized()
gov.loc.repository.bagit.verify.MandatoryVerifier.checkIfAtLeastOnePayloadManifestsExist()
gov.loc.repository.bagit.verify.PayloadVerifier.getAllFilesListedInManifests()

**Comment by johnscancella** [comment]
Thanks @smmorrissey for the great testing! I am looking into why FindBugs didn't report that as an error
