### ISSUE TITLE
Add ability to control number of threads used to verify bag in PayloadVerifier

### ISSUE THREAD

**Issue by smmorrissey** [LibraryOfCongress/bagit-java#87]
**As** 
*someone with a bag to verify

**When** 
*I verify the bag

**Then** 
*I should be able to control the number of threads used

This was dealt with in Issue #71, but refactoring reintroduced the creation of  threadpool with an unlimited number of threads in PayloadVerifier.checkAllFilesListedInManifestExist().  
We run Bagit within an application that is itself multithreaded, and we need to tune the number of threads we alot to the application (lots going on on the machine) --Creating threadpools of uncontrolled size is causing serious resource contention in our system

note also BagVerifier.checkHashes() should issue executor.shutdown()

**Comment by smmorrissey** [comment]
Also I think, in BagVerifier.checkHashes(), you might want to use a synchronized list to pass to the CheckManifestHashsTask
final List<Exception> exceptions = Collections.synchronizedList(new ArrayList<>());

**Comment by smmorrissey** [comment]
Also in PayloadVerifier.checkAllFilesListedInManifestExist()
final List<Path> missingFiles = Collections.synchronizedList(new ArrayList<>());

**Comment by johnscancella** [comment]
Thanks for submitting this, we will try and look at it soon! If you are able, please submit a pull request with the suggested changes from above. We will work with you to incorporate it into the baseline, and add tests so that this doesn't happen again.

**Comment by smmorrissey** [comment]
John As soon as we get it tested out, will post the changes, at very least as a gist

**Comment by johnscancella** [comment]
I added finalizers so that should prevent any memory leaks from the thread pool not being closed. The use of `Collections.synchronizedList` doesn't add anything since we wait for all the threads to finish before accessing. We also don't want care about ordering in this case, so it is ok for many threads to do `list.add()`.

**Comment by smmorrissey** [comment]
CheckManifestshashsTask.run() adds to the list, as does CheckIfFileExistsTask.run() (i.e multiple threads could be adding at once)
