### ISSUE TITLE
file modification leaves files unusable

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagit-java#91]
From https://github.com/LibraryOfCongress/bagger/issues/44
Since it has something to do with bagit-java and not bagger creating the issue here

For some reason when the user is creating a bag and saving it to a different directory, some (all?) of the files are slightly modified and thus are now unusable

**Comment by BenHoutman** [comment]
Hello, 
I recently downloaded Bagger to create a bag in a different directory because I did not want to write anything onto the original drive, which I had mounted read-only. The copies in the destination ended up being slightly smaller that the originals and naturally wouldn't play or function as they should. John suggested I try it in the command line using the Java version of Bagit to see if it was a bagger problem or a Bagit problem. Unfortunately the same problem happened in the command line, so here we are. Most of the information is in the link provided by John, but if other information is necessary, I'd be happy to share if it helps solve a problem. 
I should note that the files transferred fine with an rsync transfer followed by bagging in place using Bagger.

**Comment by BenHoutman** [comment]
Just checking in to see if there is an explanation for why this would happen, or if more information is needed.

**Comment by johnscancella** [comment]
@BenHoutman could you send me the original file and the messed up file so I can compare them?

**Comment by BenHoutman** [comment]
Hi John,
The files that have been damaged are quicktime and lifeforms files, which I can't add here. Can I send you them another way?

**Comment by johnscancella** [comment]
to add them here just change the file extension to `.txt`

**Comment by BenHoutman** [comment]
[armsout.txt](https://github.com/LibraryOfCongress/bagit-java/files/1116348/armsout.txt)
[armsout.txt](https://github.com/LibraryOfCongress/bagit-java/files/1116352/armsout.txt)

[MALE SOLO FIGURE.txt](https://github.com/LibraryOfCongress/bagit-java/files/1116361/MALE.SOLO.FIGURE.txt)
[MALE SOLO FIGURE.txt](https://github.com/LibraryOfCongress/bagit-java/files/1116362/MALE.SOLO.FIGURE.txt)

**Comment by BenHoutman** [comment]
In each case the second file should be the functional one and the first the non.

**Comment by johnscancella** [comment]
Are you sure that they uploaded correctly? There doesn't appear to be any difference between them for me.

**Comment by BenHoutman** [comment]
[SPLIT SIDE SOLO_performance.txt](https://github.com/LibraryOfCongress/bagit-java/files/1131906/SPLIT.SIDE.SOLO_performance.txt)
[SPLIT SIDE SOLO_performance_functional.txt](https://github.com/LibraryOfCongress/bagit-java/files/1131907/SPLIT.SIDE.SOLO_performance_functional.txt)

[SPLIT SIDE SOLO performance.txt](https://github.com/LibraryOfCongress/bagit-java/files/1132008/SPLIT.SIDE.SOLO.performance.txt)
[SPLIT SIDE SOLO do not use.txt](https://github.com/LibraryOfCongress/bagit-java/files/1132011/SPLIT.SIDE.SOLO.do.not.use.txt)

Hi John, 
I've added two quicktime videos of the solo from Split Sides (at top), which differ by 3523 bytes (5,012,485 v 5,007,962) and two dance forms files (.lfa) from Split Sides, which differ by 1302 bytes. In the case of the .lfa files, the damaged files do play, but I still wonder what might be missing with those 1302 bytes (42448 v 41146).

**Comment by johnscancella** [comment]
Nope, you can see that they are the same length
```
-rw-r--r--@ 1 jscancella  staff    41146 Jul  7 15:06 SPLIT.SIDE.SOLO.do.not.use.txt
-rw-r--r--@ 1 jscancella  staff    41146 Jul  7 15:06 SPLIT.SIDE.SOLO.performance.txt
-rw-r--r--@ 1 jscancella  staff  5008962 Jul  7 15:06 SPLIT.SIDE.SOLO_performance.txt
-rw-r--r--@ 1 jscancella  staff  5008962 Jul  7 15:06 SPLIT.SIDE.SOLO_performance_functional.txt
```
I also did a binary comparison and they are exactly the same.

**Comment by BenHoutman** [comment]
![screen shot 2017-07-11 at 7 17 53 pm](https://user-images.githubusercontent.com/29440483/28094980-dbfe1904-666d-11e7-819c-0017fabd2291.png)
Interesting. I just got the same results.
Do you have any thoughts as to why the file sizes would display differently in finder and the files act differently in playback?

**Comment by johnscancella** [comment]
Try zipping up the two files named "SPLIT SIDE SOLO.lfa" and attaching it here. Github must be doing something to the files because the ones I keep getting are the same.

**Comment by acdha** [comment]
A couple questions which came to mind:

* Do you have an anti-virus package or something similar which could be filtering disk I/O?
* What type of filesystem are the source and destination drives?
* For the successfully rsynced files, `/sbin/md5` does return the same hash for both the source and destination copies, right?

**Comment by BenHoutman** [comment]
We run Norton antivirus on this computer
The source filesystem is MacOS Extended
The destination filesystem is MacOS Extended (journaled)
The checksums match for the source drive and the rsynced folders. 
I attach a zipped folder with the two split side solo lfa files. They could very well be the same, but they keep showing up as different for whatever reason, with the rsynced files working normally and appearing similarly to the original files and the bagit java files acting strangely. 

[untitled folder 2.zip](https://github.com/LibraryOfCongress/bagit-java/files/1149712/untitled.folder.2.zip)

**Comment by johnscancella** [comment]
The zipped files are still showing up the same for me. Bit for Bit they are exactly the same.
