### ISSUE TITLE
ArrayIndexOutOfBoundsException while reading fetch.txt

### ISSUE THREAD

**Issue by rvanheest** [LibraryOfCongress/bagit-java#92]
We've started to switch from v4 to v5 and so far it has been a great joy! I especially like the extended error messages for errors in the input regarding (for example `bagit.txt` and `bag-info.txt`). These error messages really help to see what went wrong while reading a bag. However, I'm missing this feature for `fetch.txt`.

Here's the situation: one of our test-bags has an extra newline at the end of the `fetch.txt` file. Because of this, the `FetchReader` fails at [line 55](https://github.com/LibraryOfCongress/bagit-java/blob/75cedbe9688c47c007334ca7ff39bbbbb882bbfe/src/main/java/gov/loc/repository/bagit/reader/FetchReader.java#L55), since the array that was filled in the previous line does not contain any items. It would be great if you could catch the exception in this part of the reader and return a similarly nice looking error message as referred to above.

**Comment by johnscancella** [comment]
I just tested it with a file that contains a newline and it worked correctly. Are you sure there isn't some whitespace (like a space or a tab) on that line? Also what system are you running on?

**Comment by rvanheest** [comment]
An example can be found here: [fetch.txt](https://github.com/LibraryOfCongress/bagit-java/files/1105394/fetch.txt). This file has an empty line at the end. The same happens when you add a newline in the middle of the file.

Full disclosure: the change in it's context can be found [here](https://github.com/DANS-KNAW/easy-bag-index/compare/master...rvanheest-DANS-KNAW:EASY-1013#diff-a35d3e0daffd4e48a75852d70eafc930).

Btw. I'm running on mac/unix.

**Comment by johnscancella** [comment]
This will be in release 5.0.1

**Comment by rvanheest** [comment]
Looks great! Added one [comment](https://github.com/LibraryOfCongress/bagit-java/commit/34e841fa7422eb07f5522406fb83942efd56ad40#commitcomment-22787287) to your commit.

Thanks for the quick response.
