### ISSUE TITLE
Create bag in place with includeHidden = true

### ISSUE THREAD

**Issue by rvanheest** [LibraryOfCongress/bagit-java#93]
When I call `BagCreator.bagInPlace` with `includeHidden = true`, the call produces a `java.nio.file.FileSystemException`. In this case it wants to move the newly created `data/` folder into itself (`data/data/`), which isn't possible.

An hour of debugging later I found out that this is because of the following code block:

```java
try(final DirectoryStream<Path> directoryStream = Files.newDirectoryStream(root)){
  for(final Path path : directoryStream){
    if(!path.equals(dataDir) && !Files.isHidden(path) || includeHidden){
      Files.move(path, dataDir.resolve(path.getFileName()));
    }
  }
}
```

Here `if(!path.equals(dataDir) && !Files.isHidden(path) || includeHidden)` must actually be `if(!path.equals(dataDir) && (!Files.isHidden(path) || includeHidden))` (extra parentheses around `!Files.isHidden(path) || includeHidden`). This has to do with [operator precedence in Java](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html): `&&` binds stronger than `||`.

In the test suite I only found a test with `includeHidden = false`, which works correctly. If you will duplicate that one with `includeHidden = true`, you will find the same error.

**Comment by rvanheest** [comment]
related to `bagInPlace`: why doesn't it generate a `bag-info.txt` also?

**Comment by johnscancella** [comment]
Thank you for reporting this issue! This is fixed in version 5.0.2.
As to why it doesn't generate a bag-info.txt is due to it being optional and there is no default values to enter into it. If other people would find this of value please up vote this comment.

**Comment by rvanheest** [comment]
Thanks for the quick response. I agree bag-info is optional, but so is tagmanifest. Maybe a basic bag-info with Payload-Oxum and bagging date would be a good start? That's what we had in version 4 of this library, if I remember correctly.

**Comment by rvanheest** [comment]
This latest commit looks great! Most of the stuff you added was added by me manually by setting the metadata elements manually and doing another `BagWriter.write` after the `BagCreator.bagInPlace`. This is way better, though! Would be happy to see the release soon.
