### ISSUE TITLE
CreateTagManifestsVistor includes entry for tagmanifest in itself

### ISSUE THREAD

**Issue by janvanmansum** [LibraryOfCongress/bagit-java#95]
## When submitting an issue please include:
* Which version you are running of the software you are running: build ac528c85f2c00fe078cebdc750238a46fd53427a
* Which operating system you are running on: Mac OS Sierra
* If available Attach all logs, and or output, and or screenshots

## Please format it in the [given when then style](http://martinfowler.com/bliki/GivenWhenThen.html)
I have coded the scenario in a [simple unit test](https://github.com/janvanmansum/bagit-java/blob/TAG_MANIFEST_CONTAINS_ITSELF/src/test/java/gov/loc/repository/bagit/hash/TagManifestUpdaterTest.java)

**Comment by johnscancella** [comment]
Hi @janvanmansum,

Thanks for submitting this issue. Could you help me understand your use case better since it is not typical to include the tagmanifest in tagmanifest listing?

Thanks

**Comment by johnscancella** [comment]
After thinking about this more, there is no meaningful way to include a valid checksum of the tag manifest in the tag manifest file. Why do you want it to include its own checksum?

**Comment by johnscancella** [comment]
closing from lack of response
