### ISSUE TITLE
CLI help page

### ISSUE THREAD

**Issue by EG-tech** [LibraryOfCongress/bagit-java#96]
Hi!

I've downloaded and installed the bagit-java library v4.12.3 as available via [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bagit.rb). I've noticed that when invoking this tool directly via the command line, the `$ bagit --help` page seems to incorrectly define usage, directing users to invoke bagit-java with the command `$ bag` when I believe it should be `$ bagit` (see attached screenshot)

I understand from the docs that access to bagit-java via CLI is no longer actively supported, but given the popularity and ease-of-use of homebrew, I know a lot of beginner users are still interested in using this version of BagIt. Could the documentation be updated to reflect the correct command? I would be happy to contribute the change myself even, but can't find where this text is defined in the repo.

Thanks!

![screen shot 2017-12-15 at 2 07 46 pm](https://user-images.githubusercontent.com/17784531/34056853-b32c8276-e1a2-11e7-9abf-cc100d41a1e0.png)

**Comment by johnscancella** [comment]
Hi @EG-tech thanks for submitting this bug. You are correct it should be `bagit` but the developer who wrote the CLI hardcoded the name `bag`. You can see that here https://github.com/LibraryOfCongress/bagit-java/blob/4.12/src/main/java/gov/loc/repository/bagit/driver/CommandLineBagDriver.java#L535

So unfortunately the only fix would be to hack the compiled jar file (not recommended) or to change the code to be dynamic and release a new version. As you know we are no longer supporting a command line version of the java library, so I believe the best would be to recommend users use the [bagit python version](https://github.com/LibraryOfCongress/bagit-python) instead.
