### ISSUE TITLE
Difference in validation status of bag using Python and Java versions

### ISSUE THREAD

**Issue by jamiepb** [LibraryOfCongress/bagit-java#97]
Hello,

I've discovered a discrepancy between the Java version and the Python version when validating a bag with an extra file. I have a bag that acquired a thumbs.db file when someone opened it. I ran a tool that is built on bagit-python (current pip install version, 1.6.2) that did not validate the bag, noting that the expected file count and bag size did not match. I then investigated and saw the thumbs.db file that had appeared after bagging. However, I then ran Bagger 2.7.6 and the bag validated. 

Software and OS:
* BagIt Python 1.6.2 and Bagger 2.7.6
* Windows 7 Enterprise

**Given** 
* A bag with a thumbs.db file in it that is not on the manifest 

**When** 
* I run a Python tool that calls bagit py 1.6.2

**Then** 
* The bag does not validate

BUT:

**Given**
* A bag with a thumbs.db file in it that is not on the manifest 

**When** 
* I open the bag in Bagger 2.7.6 and validate

**Then** 
* The validation is successful

Thank you for looking into it.

**Comment by johnscancella** [comment]
Hi @jamiepb! Thanks for submitting this issue. However, this is the bagit-java project, not the bagger project. You can find the bagger project here: https://github.com/LibraryOfCongress/bagger

I recreated your issue on the bagger project, which you can track here: https://github.com/LibraryOfCongress/bagger/issues/50

**Comment by jamiepb** [comment]
Hi John,

I see, thank you for submitting it to the right place.

Sincerely,

Jamie

JAMIE PATRICK-BURNS
Digital Archivist
State Archives of North Carolina

215 N Blount St MSC 4615 Raleigh, NC 27699
919 807 7355 office

[cid:image001.png@01D37B0E.D2086340]

Email correspondence to and from this address is subject to the North Carolina
Public Records Law and may be disclosed to third parties.

Facebook<http://www.facebook.com/NorthCarolinaCulture>  Twitter<http://www.twitter.com/ncculture>  Instagram<http://www.instagram.com/ncculture>  YouTube<http://www.youtube.com/ncculture>
